name: Park Jaehyun
url: https://21600285-jaehyunpark.github.io/
description: new page

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
